[package]
name = "ditto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_ux = "0.1.3"
phf = { version = "0.11.1", features = ["macros"] }
