pub struct Species {
    pub name: &'static str,
    pub base_hp: u8,
    pub base_attack: u8,
    pub base_defense: u8,
    pub base_special_attack: u8,
    pub base_special_defense: u8,
    pub base_speed: u8,
}

pub const SPECIES: [Species; 251] = [
    Species {
        name: "Bulbasaur",
        base_hp: 45,
        base_attack: 49,
        base_defense: 49,
        base_special_attack: 65,
        base_special_defense: 65,
        base_speed: 45,
    },
    Species {
        name: "Ivysaur",
        base_hp: 60,
        base_attack: 62,
        base_defense: 63,
        base_special_attack: 80,
        base_special_defense: 80,
        base_speed: 60,
    },
    Species {
        name: "Venusaur",
        base_hp: 80,
        base_attack: 82,
        base_defense: 83,
        base_special_attack: 100,
        base_special_defense: 100,
        base_speed: 80,
    },
    Species {
        name: "Charmander",
        base_hp: 39,
        base_attack: 52,
        base_defense: 43,
        base_special_attack: 60,
        base_special_defense: 50,
        base_speed: 65,
    },
    Species {
        name: "Charmeleon",
        base_hp: 58,
        base_attack: 64,
        base_defense: 58,
        base_special_attack: 80,
        base_special_defense: 65,
        base_speed: 80,
    },
    Species {
        name: "Charizard",
        base_hp: 78,
        base_attack: 84,
        base_defense: 78,
        base_special_attack: 109,
        base_special_defense: 85,
        base_speed: 100,
    },
    Species {
        name: "Squirtle",
        base_hp: 44,
        base_attack: 48,
        base_defense: 65,
        base_special_attack: 50,
        base_special_defense: 64,
        base_speed: 43,
    },
    Species {
        name: "Wartortle",
        base_hp: 59,
        base_attack: 63,
        base_defense: 80,
        base_special_attack: 65,
        base_special_defense: 80,
        base_speed: 58,
    },
    Species {
        name: "Blastoise",
        base_hp: 79,
        base_attack: 83,
        base_defense: 100,
        base_special_attack: 85,
        base_special_defense: 105,
        base_speed: 78,
    },
    Species {
        name: "Caterpie",
        base_hp: 45,
        base_attack: 30,
        base_defense: 35,
        base_special_attack: 20,
        base_special_defense: 20,
        base_speed: 45,
    },
    Species {
        name: "Metapod",
        base_hp: 50,
        base_attack: 20,
        base_defense: 55,
        base_special_attack: 25,
        base_special_defense: 25,
        base_speed: 30,
    },
    Species {
        name: "Butterfree",
        base_hp: 60,
        base_attack: 45,
        base_defense: 50,
        base_special_attack: 80,
        base_special_defense: 80,
        base_speed: 70,
    },
    Species {
        name: "Weedle",
        base_hp: 40,
        base_attack: 35,
        base_defense: 30,
        base_special_attack: 20,
        base_special_defense: 20,
        base_speed: 50,
    },
    Species {
        name: "Kakuna",
        base_hp: 45,
        base_attack: 25,
        base_defense: 50,
        base_special_attack: 25,
        base_special_defense: 25,
        base_speed: 35,
    },
    Species {
        name: "Beedrill",
        base_hp: 65,
        base_attack: 80,
        base_defense: 40,
        base_special_attack: 45,
        base_special_defense: 80,
        base_speed: 75,
    },
    Species {
        name: "Pidgey",
        base_hp: 40,
        base_attack: 45,
        base_defense: 40,
        base_special_attack: 35,
        base_special_defense: 35,
        base_speed: 56,
    },
    Species {
        name: "Pidgeotto",
        base_hp: 63,
        base_attack: 60,
        base_defense: 55,
        base_special_attack: 50,
        base_special_defense: 50,
        base_speed: 71,
    },
    Species {
        name: "Pidgeot",
        base_hp: 83,
        base_attack: 80,
        base_defense: 75,
        base_special_attack: 70,
        base_special_defense: 70,
        base_speed: 91,
    },
    Species {
        name: "Rattata",
        base_hp: 30,
        base_attack: 56,
        base_defense: 35,
        base_special_attack: 25,
        base_special_defense: 35,
        base_speed: 72,
    },
    Species {
        name: "Raticate",
        base_hp: 55,
        base_attack: 81,
        base_defense: 60,
        base_special_attack: 50,
        base_special_defense: 70,
        base_speed: 97,
    },
    Species {
        name: "Spearow",
        base_hp: 40,
        base_attack: 60,
        base_defense: 30,
        base_special_attack: 31,
        base_special_defense: 31,
        base_speed: 70,
    },
    Species {
        name: "Fearow",
        base_hp: 65,
        base_attack: 90,
        base_defense: 65,
        base_special_attack: 61,
        base_special_defense: 61,
        base_speed: 100,
    },
    Species {
        name: "Ekans",
        base_hp: 35,
        base_attack: 60,
        base_defense: 44,
        base_special_attack: 40,
        base_special_defense: 54,
        base_speed: 55,
    },
    Species {
        name: "Arbok",
        base_hp: 60,
        base_attack: 85,
        base_defense: 69,
        base_special_attack: 65,
        base_special_defense: 79,
        base_speed: 80,
    },
    Species {
        name: "Pikachu",
        base_hp: 35,
        base_attack: 55,
        base_defense: 30,
        base_special_attack: 50,
        base_special_defense: 40,
        base_speed: 90,
    },
    Species {
        name: "Raichu",
        base_hp: 60,
        base_attack: 90,
        base_defense: 55,
        base_special_attack: 90,
        base_special_defense: 80,
        base_speed: 100,
    },
    Species {
        name: "Sandshrew",
        base_hp: 50,
        base_attack: 75,
        base_defense: 85,
        base_special_attack: 20,
        base_special_defense: 30,
        base_speed: 40,
    },
    Species {
        name: "Sandslash",
        base_hp: 75,
        base_attack: 100,
        base_defense: 110,
        base_special_attack: 45,
        base_special_defense: 55,
        base_speed: 65,
    },
    Species {
        name: "Nidoran♀",
        base_hp: 55,
        base_attack: 47,
        base_defense: 52,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 41,
    },
    Species {
        name: "Nidorina",
        base_hp: 70,
        base_attack: 62,
        base_defense: 67,
        base_special_attack: 55,
        base_special_defense: 55,
        base_speed: 56,
    },
    Species {
        name: "Nidoqueen",
        base_hp: 90,
        base_attack: 82,
        base_defense: 87,
        base_special_attack: 75,
        base_special_defense: 85,
        base_speed: 76,
    },
    Species {
        name: "Nidoran♂",
        base_hp: 46,
        base_attack: 57,
        base_defense: 40,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 50,
    },
    Species {
        name: "Nidorino",
        base_hp: 61,
        base_attack: 72,
        base_defense: 57,
        base_special_attack: 55,
        base_special_defense: 55,
        base_speed: 65,
    },
    Species {
        name: "Nidoking",
        base_hp: 81,
        base_attack: 92,
        base_defense: 77,
        base_special_attack: 85,
        base_special_defense: 75,
        base_speed: 85,
    },
    Species {
        name: "Clefairy",
        base_hp: 70,
        base_attack: 45,
        base_defense: 48,
        base_special_attack: 60,
        base_special_defense: 65,
        base_speed: 35,
    },
    Species {
        name: "Clefable",
        base_hp: 95,
        base_attack: 70,
        base_defense: 73,
        base_special_attack: 85,
        base_special_defense: 90,
        base_speed: 60,
    },
    Species {
        name: "Vulpix",
        base_hp: 38,
        base_attack: 41,
        base_defense: 40,
        base_special_attack: 50,
        base_special_defense: 65,
        base_speed: 65,
    },
    Species {
        name: "Ninetales",
        base_hp: 73,
        base_attack: 76,
        base_defense: 75,
        base_special_attack: 81,
        base_special_defense: 100,
        base_speed: 100,
    },
    Species {
        name: "Jigglypuff",
        base_hp: 115,
        base_attack: 45,
        base_defense: 20,
        base_special_attack: 45,
        base_special_defense: 25,
        base_speed: 20,
    },
    Species {
        name: "Wigglytuff",
        base_hp: 140,
        base_attack: 70,
        base_defense: 45,
        base_special_attack: 75,
        base_special_defense: 50,
        base_speed: 45,
    },
    Species {
        name: "Zubat",
        base_hp: 40,
        base_attack: 45,
        base_defense: 35,
        base_special_attack: 30,
        base_special_defense: 40,
        base_speed: 55,
    },
    Species {
        name: "Golbat",
        base_hp: 75,
        base_attack: 80,
        base_defense: 70,
        base_special_attack: 65,
        base_special_defense: 75,
        base_speed: 90,
    },
    Species {
        name: "Oddish",
        base_hp: 45,
        base_attack: 50,
        base_defense: 55,
        base_special_attack: 75,
        base_special_defense: 65,
        base_speed: 30,
    },
    Species {
        name: "Gloom",
        base_hp: 60,
        base_attack: 65,
        base_defense: 70,
        base_special_attack: 85,
        base_special_defense: 75,
        base_speed: 40,
    },
    Species {
        name: "Vileplume",
        base_hp: 75,
        base_attack: 80,
        base_defense: 85,
        base_special_attack: 100,
        base_special_defense: 90,
        base_speed: 50,
    },
    Species {
        name: "Paras",
        base_hp: 35,
        base_attack: 70,
        base_defense: 55,
        base_special_attack: 45,
        base_special_defense: 55,
        base_speed: 25,
    },
    Species {
        name: "Parasect",
        base_hp: 60,
        base_attack: 95,
        base_defense: 80,
        base_special_attack: 60,
        base_special_defense: 80,
        base_speed: 30,
    },
    Species {
        name: "Venonat",
        base_hp: 60,
        base_attack: 55,
        base_defense: 50,
        base_special_attack: 40,
        base_special_defense: 55,
        base_speed: 45,
    },
    Species {
        name: "Venomoth",
        base_hp: 70,
        base_attack: 65,
        base_defense: 60,
        base_special_attack: 90,
        base_special_defense: 75,
        base_speed: 90,
    },
    Species {
        name: "Diglett",
        base_hp: 10,
        base_attack: 55,
        base_defense: 25,
        base_special_attack: 35,
        base_special_defense: 45,
        base_speed: 95,
    },
    Species {
        name: "Dugtrio",
        base_hp: 35,
        base_attack: 80,
        base_defense: 50,
        base_special_attack: 50,
        base_special_defense: 70,
        base_speed: 120,
    },
    Species {
        name: "Meowth",
        base_hp: 40,
        base_attack: 45,
        base_defense: 35,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 90,
    },
    Species {
        name: "Persian",
        base_hp: 65,
        base_attack: 70,
        base_defense: 60,
        base_special_attack: 65,
        base_special_defense: 65,
        base_speed: 115,
    },
    Species {
        name: "Psyduck",
        base_hp: 50,
        base_attack: 52,
        base_defense: 48,
        base_special_attack: 65,
        base_special_defense: 50,
        base_speed: 55,
    },
    Species {
        name: "Golduck",
        base_hp: 80,
        base_attack: 82,
        base_defense: 78,
        base_special_attack: 95,
        base_special_defense: 80,
        base_speed: 85,
    },
    Species {
        name: "Mankey",
        base_hp: 40,
        base_attack: 80,
        base_defense: 35,
        base_special_attack: 35,
        base_special_defense: 45,
        base_speed: 70,
    },
    Species {
        name: "Primeape",
        base_hp: 65,
        base_attack: 105,
        base_defense: 60,
        base_special_attack: 60,
        base_special_defense: 70,
        base_speed: 95,
    },
    Species {
        name: "Growlithe",
        base_hp: 55,
        base_attack: 70,
        base_defense: 45,
        base_special_attack: 70,
        base_special_defense: 50,
        base_speed: 60,
    },
    Species {
        name: "Arcanine",
        base_hp: 90,
        base_attack: 110,
        base_defense: 80,
        base_special_attack: 100,
        base_special_defense: 80,
        base_speed: 95,
    },
    Species {
        name: "Poliwag",
        base_hp: 40,
        base_attack: 50,
        base_defense: 40,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 90,
    },
    Species {
        name: "Poliwhirl",
        base_hp: 65,
        base_attack: 65,
        base_defense: 65,
        base_special_attack: 50,
        base_special_defense: 50,
        base_speed: 90,
    },
    Species {
        name: "Poliwrath",
        base_hp: 90,
        base_attack: 85,
        base_defense: 95,
        base_special_attack: 70,
        base_special_defense: 90,
        base_speed: 70,
    },
    Species {
        name: "Abra",
        base_hp: 25,
        base_attack: 20,
        base_defense: 15,
        base_special_attack: 105,
        base_special_defense: 55,
        base_speed: 90,
    },
    Species {
        name: "Kadabra",
        base_hp: 40,
        base_attack: 35,
        base_defense: 30,
        base_special_attack: 120,
        base_special_defense: 70,
        base_speed: 105,
    },
    Species {
        name: "Alakazam",
        base_hp: 55,
        base_attack: 50,
        base_defense: 45,
        base_special_attack: 135,
        base_special_defense: 85,
        base_speed: 120,
    },
    Species {
        name: "Machop",
        base_hp: 70,
        base_attack: 80,
        base_defense: 50,
        base_special_attack: 35,
        base_special_defense: 35,
        base_speed: 35,
    },
    Species {
        name: "Machoke",
        base_hp: 80,
        base_attack: 100,
        base_defense: 70,
        base_special_attack: 50,
        base_special_defense: 60,
        base_speed: 45,
    },
    Species {
        name: "Machamp",
        base_hp: 90,
        base_attack: 130,
        base_defense: 80,
        base_special_attack: 65,
        base_special_defense: 85,
        base_speed: 55,
    },
    Species {
        name: "Bellsprout",
        base_hp: 50,
        base_attack: 75,
        base_defense: 35,
        base_special_attack: 70,
        base_special_defense: 30,
        base_speed: 40,
    },
    Species {
        name: "Weepinbell",
        base_hp: 65,
        base_attack: 90,
        base_defense: 50,
        base_special_attack: 85,
        base_special_defense: 45,
        base_speed: 55,
    },
    Species {
        name: "Victreebel",
        base_hp: 80,
        base_attack: 105,
        base_defense: 65,
        base_special_attack: 100,
        base_special_defense: 60,
        base_speed: 70,
    },
    Species {
        name: "Tentacool",
        base_hp: 40,
        base_attack: 40,
        base_defense: 35,
        base_special_attack: 50,
        base_special_defense: 100,
        base_speed: 70,
    },
    Species {
        name: "Tentacruel",
        base_hp: 80,
        base_attack: 70,
        base_defense: 65,
        base_special_attack: 80,
        base_special_defense: 120,
        base_speed: 100,
    },
    Species {
        name: "Geodude",
        base_hp: 40,
        base_attack: 80,
        base_defense: 100,
        base_special_attack: 30,
        base_special_defense: 30,
        base_speed: 20,
    },
    Species {
        name: "Graveler",
        base_hp: 55,
        base_attack: 95,
        base_defense: 115,
        base_special_attack: 45,
        base_special_defense: 45,
        base_speed: 35,
    },
    Species {
        name: "Golem",
        base_hp: 80,
        base_attack: 110,
        base_defense: 130,
        base_special_attack: 55,
        base_special_defense: 65,
        base_speed: 45,
    },
    Species {
        name: "Ponyta",
        base_hp: 50,
        base_attack: 85,
        base_defense: 55,
        base_special_attack: 65,
        base_special_defense: 65,
        base_speed: 90,
    },
    Species {
        name: "Rapidash",
        base_hp: 65,
        base_attack: 100,
        base_defense: 70,
        base_special_attack: 80,
        base_special_defense: 80,
        base_speed: 105,
    },
    Species {
        name: "Slowpoke",
        base_hp: 90,
        base_attack: 65,
        base_defense: 65,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 15,
    },
    Species {
        name: "Slowbro",
        base_hp: 95,
        base_attack: 75,
        base_defense: 110,
        base_special_attack: 100,
        base_special_defense: 80,
        base_speed: 30,
    },
    Species {
        name: "Magnemite",
        base_hp: 25,
        base_attack: 35,
        base_defense: 70,
        base_special_attack: 95,
        base_special_defense: 55,
        base_speed: 45,
    },
    Species {
        name: "Magneton",
        base_hp: 50,
        base_attack: 60,
        base_defense: 95,
        base_special_attack: 120,
        base_special_defense: 70,
        base_speed: 70,
    },
    Species {
        name: "Farfetch'd",
        base_hp: 52,
        base_attack: 65,
        base_defense: 55,
        base_special_attack: 58,
        base_special_defense: 62,
        base_speed: 60,
    },
    Species {
        name: "Doduo",
        base_hp: 35,
        base_attack: 85,
        base_defense: 45,
        base_special_attack: 35,
        base_special_defense: 35,
        base_speed: 75,
    },
    Species {
        name: "Dodrio",
        base_hp: 60,
        base_attack: 110,
        base_defense: 70,
        base_special_attack: 60,
        base_special_defense: 60,
        base_speed: 100,
    },
    Species {
        name: "Seel",
        base_hp: 65,
        base_attack: 45,
        base_defense: 55,
        base_special_attack: 45,
        base_special_defense: 70,
        base_speed: 45,
    },
    Species {
        name: "Dewgong",
        base_hp: 90,
        base_attack: 70,
        base_defense: 80,
        base_special_attack: 70,
        base_special_defense: 95,
        base_speed: 70,
    },
    Species {
        name: "Grimer",
        base_hp: 80,
        base_attack: 80,
        base_defense: 50,
        base_special_attack: 40,
        base_special_defense: 50,
        base_speed: 25,
    },
    Species {
        name: "Muk",
        base_hp: 105,
        base_attack: 105,
        base_defense: 75,
        base_special_attack: 65,
        base_special_defense: 100,
        base_speed: 50,
    },
    Species {
        name: "Shellder",
        base_hp: 30,
        base_attack: 65,
        base_defense: 100,
        base_special_attack: 45,
        base_special_defense: 25,
        base_speed: 40,
    },
    Species {
        name: "Cloyster",
        base_hp: 50,
        base_attack: 95,
        base_defense: 180,
        base_special_attack: 85,
        base_special_defense: 45,
        base_speed: 70,
    },
    Species {
        name: "Gastly",
        base_hp: 30,
        base_attack: 35,
        base_defense: 30,
        base_special_attack: 100,
        base_special_defense: 35,
        base_speed: 80,
    },
    Species {
        name: "Haunter",
        base_hp: 45,
        base_attack: 50,
        base_defense: 45,
        base_special_attack: 115,
        base_special_defense: 55,
        base_speed: 95,
    },
    Species {
        name: "Gengar",
        base_hp: 60,
        base_attack: 65,
        base_defense: 60,
        base_special_attack: 130,
        base_special_defense: 75,
        base_speed: 110,
    },
    Species {
        name: "Onix",
        base_hp: 35,
        base_attack: 45,
        base_defense: 160,
        base_special_attack: 30,
        base_special_defense: 45,
        base_speed: 70,
    },
    Species {
        name: "Drowzee",
        base_hp: 60,
        base_attack: 48,
        base_defense: 45,
        base_special_attack: 43,
        base_special_defense: 90,
        base_speed: 42,
    },
    Species {
        name: "Hypno",
        base_hp: 85,
        base_attack: 73,
        base_defense: 70,
        base_special_attack: 73,
        base_special_defense: 115,
        base_speed: 67,
    },
    Species {
        name: "Krabby",
        base_hp: 30,
        base_attack: 105,
        base_defense: 90,
        base_special_attack: 25,
        base_special_defense: 25,
        base_speed: 50,
    },
    Species {
        name: "Kingler",
        base_hp: 55,
        base_attack: 130,
        base_defense: 115,
        base_special_attack: 50,
        base_special_defense: 50,
        base_speed: 75,
    },
    Species {
        name: "Voltorb",
        base_hp: 40,
        base_attack: 30,
        base_defense: 50,
        base_special_attack: 55,
        base_special_defense: 55,
        base_speed: 100,
    },
    Species {
        name: "Electrode",
        base_hp: 60,
        base_attack: 50,
        base_defense: 70,
        base_special_attack: 80,
        base_special_defense: 80,
        base_speed: 140,
    },
    Species {
        name: "Exeggcute",
        base_hp: 60,
        base_attack: 40,
        base_defense: 80,
        base_special_attack: 60,
        base_special_defense: 45,
        base_speed: 40,
    },
    Species {
        name: "Exeggutor",
        base_hp: 95,
        base_attack: 95,
        base_defense: 85,
        base_special_attack: 125,
        base_special_defense: 65,
        base_speed: 55,
    },
    Species {
        name: "Cubone",
        base_hp: 50,
        base_attack: 50,
        base_defense: 95,
        base_special_attack: 40,
        base_special_defense: 50,
        base_speed: 35,
    },
    Species {
        name: "Marowak",
        base_hp: 60,
        base_attack: 80,
        base_defense: 110,
        base_special_attack: 50,
        base_special_defense: 80,
        base_speed: 45,
    },
    Species {
        name: "Hitmonlee",
        base_hp: 50,
        base_attack: 120,
        base_defense: 53,
        base_special_attack: 35,
        base_special_defense: 110,
        base_speed: 87,
    },
    Species {
        name: "Hitmonchan",
        base_hp: 50,
        base_attack: 105,
        base_defense: 79,
        base_special_attack: 35,
        base_special_defense: 110,
        base_speed: 76,
    },
    Species {
        name: "Lickitung",
        base_hp: 90,
        base_attack: 55,
        base_defense: 75,
        base_special_attack: 60,
        base_special_defense: 75,
        base_speed: 30,
    },
    Species {
        name: "Koffing",
        base_hp: 40,
        base_attack: 65,
        base_defense: 95,
        base_special_attack: 60,
        base_special_defense: 45,
        base_speed: 35,
    },
    Species {
        name: "Weezing",
        base_hp: 65,
        base_attack: 90,
        base_defense: 120,
        base_special_attack: 85,
        base_special_defense: 70,
        base_speed: 60,
    },
    Species {
        name: "Rhyhorn",
        base_hp: 80,
        base_attack: 85,
        base_defense: 95,
        base_special_attack: 30,
        base_special_defense: 30,
        base_speed: 25,
    },
    Species {
        name: "Rhydon",
        base_hp: 105,
        base_attack: 130,
        base_defense: 120,
        base_special_attack: 45,
        base_special_defense: 45,
        base_speed: 40,
    },
    Species {
        name: "Chansey",
        base_hp: 250,
        base_attack: 5,
        base_defense: 5,
        base_special_attack: 35,
        base_special_defense: 105,
        base_speed: 50,
    },
    Species {
        name: "Tangela",
        base_hp: 65,
        base_attack: 55,
        base_defense: 115,
        base_special_attack: 100,
        base_special_defense: 40,
        base_speed: 60,
    },
    Species {
        name: "Kangaskhan",
        base_hp: 105,
        base_attack: 95,
        base_defense: 80,
        base_special_attack: 40,
        base_special_defense: 80,
        base_speed: 90,
    },
    Species {
        name: "Horsea",
        base_hp: 30,
        base_attack: 40,
        base_defense: 70,
        base_special_attack: 70,
        base_special_defense: 25,
        base_speed: 60,
    },
    Species {
        name: "Seadra",
        base_hp: 55,
        base_attack: 65,
        base_defense: 95,
        base_special_attack: 95,
        base_special_defense: 45,
        base_speed: 85,
    },
    Species {
        name: "Goldeen",
        base_hp: 45,
        base_attack: 67,
        base_defense: 60,
        base_special_attack: 35,
        base_special_defense: 50,
        base_speed: 63,
    },
    Species {
        name: "Seaking",
        base_hp: 80,
        base_attack: 92,
        base_defense: 65,
        base_special_attack: 65,
        base_special_defense: 80,
        base_speed: 68,
    },
    Species {
        name: "Staryu",
        base_hp: 30,
        base_attack: 45,
        base_defense: 55,
        base_special_attack: 70,
        base_special_defense: 55,
        base_speed: 85,
    },
    Species {
        name: "Starmie",
        base_hp: 60,
        base_attack: 75,
        base_defense: 85,
        base_special_attack: 100,
        base_special_defense: 85,
        base_speed: 115,
    },
    Species {
        name: "Mr. Mime",
        base_hp: 40,
        base_attack: 45,
        base_defense: 65,
        base_special_attack: 100,
        base_special_defense: 120,
        base_speed: 90,
    },
    Species {
        name: "Scyther",
        base_hp: 70,
        base_attack: 110,
        base_defense: 80,
        base_special_attack: 55,
        base_special_defense: 80,
        base_speed: 105,
    },
    Species {
        name: "Jynx",
        base_hp: 65,
        base_attack: 50,
        base_defense: 35,
        base_special_attack: 115,
        base_special_defense: 95,
        base_speed: 95,
    },
    Species {
        name: "Electabuzz",
        base_hp: 65,
        base_attack: 83,
        base_defense: 57,
        base_special_attack: 95,
        base_special_defense: 85,
        base_speed: 105,
    },
    Species {
        name: "Magmar",
        base_hp: 65,
        base_attack: 95,
        base_defense: 57,
        base_special_attack: 100,
        base_special_defense: 85,
        base_speed: 93,
    },
    Species {
        name: "Pinsir",
        base_hp: 65,
        base_attack: 125,
        base_defense: 100,
        base_special_attack: 55,
        base_special_defense: 70,
        base_speed: 85,
    },
    Species {
        name: "Tauros",
        base_hp: 75,
        base_attack: 100,
        base_defense: 95,
        base_special_attack: 40,
        base_special_defense: 70,
        base_speed: 110,
    },
    Species {
        name: "Magikarp",
        base_hp: 20,
        base_attack: 10,
        base_defense: 55,
        base_special_attack: 15,
        base_special_defense: 20,
        base_speed: 80,
    },
    Species {
        name: "Gyarados",
        base_hp: 95,
        base_attack: 125,
        base_defense: 79,
        base_special_attack: 60,
        base_special_defense: 100,
        base_speed: 81,
    },
    Species {
        name: "Lapras",
        base_hp: 130,
        base_attack: 85,
        base_defense: 80,
        base_special_attack: 85,
        base_special_defense: 95,
        base_speed: 60,
    },
    Species {
        name: "Ditto",
        base_hp: 48,
        base_attack: 48,
        base_defense: 48,
        base_special_attack: 48,
        base_special_defense: 48,
        base_speed: 48,
    },
    Species {
        name: "Eevee",
        base_hp: 55,
        base_attack: 55,
        base_defense: 50,
        base_special_attack: 45,
        base_special_defense: 65,
        base_speed: 55,
    },
    Species {
        name: "Vaporeon",
        base_hp: 130,
        base_attack: 65,
        base_defense: 60,
        base_special_attack: 110,
        base_special_defense: 95,
        base_speed: 65,
    },
    Species {
        name: "Jolteon",
        base_hp: 65,
        base_attack: 65,
        base_defense: 60,
        base_special_attack: 110,
        base_special_defense: 95,
        base_speed: 130,
    },
    Species {
        name: "Flareon",
        base_hp: 65,
        base_attack: 130,
        base_defense: 60,
        base_special_attack: 95,
        base_special_defense: 110,
        base_speed: 65,
    },
    Species {
        name: "Porygon",
        base_hp: 65,
        base_attack: 60,
        base_defense: 70,
        base_special_attack: 85,
        base_special_defense: 75,
        base_speed: 40,
    },
    Species {
        name: "Omanyte",
        base_hp: 35,
        base_attack: 40,
        base_defense: 100,
        base_special_attack: 90,
        base_special_defense: 55,
        base_speed: 35,
    },
    Species {
        name: "Omastar",
        base_hp: 70,
        base_attack: 60,
        base_defense: 125,
        base_special_attack: 115,
        base_special_defense: 70,
        base_speed: 55,
    },
    Species {
        name: "Kabuto",
        base_hp: 30,
        base_attack: 80,
        base_defense: 90,
        base_special_attack: 55,
        base_special_defense: 45,
        base_speed: 55,
    },
    Species {
        name: "Kabutops",
        base_hp: 60,
        base_attack: 115,
        base_defense: 105,
        base_special_attack: 65,
        base_special_defense: 70,
        base_speed: 80,
    },
    Species {
        name: "Aerodactyl",
        base_hp: 80,
        base_attack: 105,
        base_defense: 65,
        base_special_attack: 60,
        base_special_defense: 75,
        base_speed: 130,
    },
    Species {
        name: "Snorlax",
        base_hp: 160,
        base_attack: 110,
        base_defense: 65,
        base_special_attack: 65,
        base_special_defense: 110,
        base_speed: 30,
    },
    Species {
        name: "Articuno",
        base_hp: 90,
        base_attack: 85,
        base_defense: 100,
        base_special_attack: 95,
        base_special_defense: 125,
        base_speed: 85,
    },
    Species {
        name: "Zapdos",
        base_hp: 90,
        base_attack: 90,
        base_defense: 85,
        base_special_attack: 125,
        base_special_defense: 90,
        base_speed: 100,
    },
    Species {
        name: "Moltres",
        base_hp: 90,
        base_attack: 100,
        base_defense: 90,
        base_special_attack: 125,
        base_special_defense: 85,
        base_speed: 90,
    },
    Species {
        name: "Dratini",
        base_hp: 41,
        base_attack: 64,
        base_defense: 45,
        base_special_attack: 50,
        base_special_defense: 50,
        base_speed: 50,
    },
    Species {
        name: "Dragonair",
        base_hp: 61,
        base_attack: 84,
        base_defense: 65,
        base_special_attack: 70,
        base_special_defense: 70,
        base_speed: 70,
    },
    Species {
        name: "Dragonite",
        base_hp: 91,
        base_attack: 134,
        base_defense: 95,
        base_special_attack: 100,
        base_special_defense: 100,
        base_speed: 80,
    },
    Species {
        name: "Mewtwo",
        base_hp: 106,
        base_attack: 110,
        base_defense: 90,
        base_special_attack: 154,
        base_special_defense: 90,
        base_speed: 130,
    },
    Species {
        name: "Mew",
        base_hp: 100,
        base_attack: 100,
        base_defense: 100,
        base_special_attack: 100,
        base_special_defense: 100,
        base_speed: 100,
    },
    Species {
        name: "Chikorita",
        base_hp: 45,
        base_attack: 49,
        base_defense: 65,
        base_special_attack: 49,
        base_special_defense: 65,
        base_speed: 45,
    },
    Species {
        name: "Bayleef",
        base_hp: 60,
        base_attack: 62,
        base_defense: 80,
        base_special_attack: 63,
        base_special_defense: 80,
        base_speed: 60,
    },
    Species {
        name: "Meganium",
        base_hp: 80,
        base_attack: 82,
        base_defense: 100,
        base_special_attack: 83,
        base_special_defense: 100,
        base_speed: 80,
    },
    Species {
        name: "Cyndaquil",
        base_hp: 39,
        base_attack: 52,
        base_defense: 43,
        base_special_attack: 60,
        base_special_defense: 50,
        base_speed: 65,
    },
    Species {
        name: "Quilava",
        base_hp: 58,
        base_attack: 64,
        base_defense: 58,
        base_special_attack: 80,
        base_special_defense: 65,
        base_speed: 80,
    },
    Species {
        name: "Typhlosion",
        base_hp: 78,
        base_attack: 84,
        base_defense: 78,
        base_special_attack: 109,
        base_special_defense: 85,
        base_speed: 100,
    },
    Species {
        name: "Totodile",
        base_hp: 50,
        base_attack: 65,
        base_defense: 64,
        base_special_attack: 44,
        base_special_defense: 48,
        base_speed: 43,
    },
    Species {
        name: "Croconaw",
        base_hp: 65,
        base_attack: 80,
        base_defense: 80,
        base_special_attack: 59,
        base_special_defense: 63,
        base_speed: 58,
    },
    Species {
        name: "Feraligatr",
        base_hp: 85,
        base_attack: 105,
        base_defense: 100,
        base_special_attack: 79,
        base_special_defense: 83,
        base_speed: 78,
    },
    Species {
        name: "Sentret",
        base_hp: 35,
        base_attack: 46,
        base_defense: 34,
        base_special_attack: 35,
        base_special_defense: 45,
        base_speed: 20,
    },
    Species {
        name: "Furret",
        base_hp: 85,
        base_attack: 76,
        base_defense: 64,
        base_special_attack: 45,
        base_special_defense: 55,
        base_speed: 90,
    },
    Species {
        name: "Hoothoot",
        base_hp: 60,
        base_attack: 30,
        base_defense: 30,
        base_special_attack: 36,
        base_special_defense: 56,
        base_speed: 50,
    },
    Species {
        name: "Noctowl",
        base_hp: 100,
        base_attack: 50,
        base_defense: 50,
        base_special_attack: 76,
        base_special_defense: 96,
        base_speed: 70,
    },
    Species {
        name: "Ledyba",
        base_hp: 40,
        base_attack: 20,
        base_defense: 30,
        base_special_attack: 40,
        base_special_defense: 80,
        base_speed: 55,
    },
    Species {
        name: "Ledian",
        base_hp: 55,
        base_attack: 35,
        base_defense: 50,
        base_special_attack: 55,
        base_special_defense: 110,
        base_speed: 85,
    },
    Species {
        name: "Spinarak",
        base_hp: 40,
        base_attack: 60,
        base_defense: 40,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 30,
    },
    Species {
        name: "Ariados",
        base_hp: 70,
        base_attack: 90,
        base_defense: 70,
        base_special_attack: 60,
        base_special_defense: 60,
        base_speed: 40,
    },
    Species {
        name: "Crobat",
        base_hp: 85,
        base_attack: 90,
        base_defense: 80,
        base_special_attack: 70,
        base_special_defense: 80,
        base_speed: 130,
    },
    Species {
        name: "Chinchou",
        base_hp: 75,
        base_attack: 38,
        base_defense: 38,
        base_special_attack: 56,
        base_special_defense: 56,
        base_speed: 67,
    },
    Species {
        name: "Lanturn",
        base_hp: 125,
        base_attack: 58,
        base_defense: 58,
        base_special_attack: 76,
        base_special_defense: 76,
        base_speed: 67,
    },
    Species {
        name: "Pichu",
        base_hp: 20,
        base_attack: 40,
        base_defense: 15,
        base_special_attack: 35,
        base_special_defense: 35,
        base_speed: 60,
    },
    Species {
        name: "Cleffa",
        base_hp: 50,
        base_attack: 25,
        base_defense: 28,
        base_special_attack: 45,
        base_special_defense: 55,
        base_speed: 15,
    },
    Species {
        name: "Igglybuff",
        base_hp: 90,
        base_attack: 30,
        base_defense: 15,
        base_special_attack: 40,
        base_special_defense: 20,
        base_speed: 15,
    },
    Species {
        name: "Togepi",
        base_hp: 35,
        base_attack: 20,
        base_defense: 65,
        base_special_attack: 40,
        base_special_defense: 65,
        base_speed: 20,
    },
    Species {
        name: "Togetic",
        base_hp: 55,
        base_attack: 40,
        base_defense: 85,
        base_special_attack: 80,
        base_special_defense: 105,
        base_speed: 40,
    },
    Species {
        name: "Natu",
        base_hp: 40,
        base_attack: 50,
        base_defense: 45,
        base_special_attack: 70,
        base_special_defense: 45,
        base_speed: 70,
    },
    Species {
        name: "Xatu",
        base_hp: 65,
        base_attack: 75,
        base_defense: 70,
        base_special_attack: 95,
        base_special_defense: 70,
        base_speed: 95,
    },
    Species {
        name: "Mareep",
        base_hp: 55,
        base_attack: 40,
        base_defense: 40,
        base_special_attack: 65,
        base_special_defense: 45,
        base_speed: 35,
    },
    Species {
        name: "Flaaffy",
        base_hp: 70,
        base_attack: 55,
        base_defense: 55,
        base_special_attack: 80,
        base_special_defense: 60,
        base_speed: 45,
    },
    Species {
        name: "Ampharos",
        base_hp: 90,
        base_attack: 75,
        base_defense: 75,
        base_special_attack: 115,
        base_special_defense: 90,
        base_speed: 55,
    },
    Species {
        name: "Bellossom",
        base_hp: 75,
        base_attack: 80,
        base_defense: 85,
        base_special_attack: 90,
        base_special_defense: 100,
        base_speed: 50,
    },
    Species {
        name: "Marill",
        base_hp: 70,
        base_attack: 20,
        base_defense: 50,
        base_special_attack: 20,
        base_special_defense: 50,
        base_speed: 40,
    },
    Species {
        name: "Azumarill",
        base_hp: 100,
        base_attack: 50,
        base_defense: 80,
        base_special_attack: 50,
        base_special_defense: 80,
        base_speed: 50,
    },
    Species {
        name: "Sudowoodo",
        base_hp: 70,
        base_attack: 100,
        base_defense: 115,
        base_special_attack: 30,
        base_special_defense: 65,
        base_speed: 30,
    },
    Species {
        name: "Politoed",
        base_hp: 90,
        base_attack: 75,
        base_defense: 75,
        base_special_attack: 90,
        base_special_defense: 100,
        base_speed: 70,
    },
    Species {
        name: "Hoppip",
        base_hp: 35,
        base_attack: 35,
        base_defense: 40,
        base_special_attack: 35,
        base_special_defense: 55,
        base_speed: 50,
    },
    Species {
        name: "Skiploom",
        base_hp: 55,
        base_attack: 45,
        base_defense: 50,
        base_special_attack: 45,
        base_special_defense: 65,
        base_speed: 80,
    },
    Species {
        name: "Jumpluff",
        base_hp: 75,
        base_attack: 55,
        base_defense: 70,
        base_special_attack: 55,
        base_special_defense: 85,
        base_speed: 110,
    },
    Species {
        name: "Aipom",
        base_hp: 55,
        base_attack: 70,
        base_defense: 55,
        base_special_attack: 40,
        base_special_defense: 55,
        base_speed: 85,
    },
    Species {
        name: "Sunkern",
        base_hp: 30,
        base_attack: 30,
        base_defense: 30,
        base_special_attack: 30,
        base_special_defense: 30,
        base_speed: 30,
    },
    Species {
        name: "Sunflora",
        base_hp: 75,
        base_attack: 75,
        base_defense: 55,
        base_special_attack: 105,
        base_special_defense: 85,
        base_speed: 30,
    },
    Species {
        name: "Yanma",
        base_hp: 65,
        base_attack: 65,
        base_defense: 45,
        base_special_attack: 75,
        base_special_defense: 45,
        base_speed: 95,
    },
    Species {
        name: "Wooper",
        base_hp: 55,
        base_attack: 45,
        base_defense: 45,
        base_special_attack: 25,
        base_special_defense: 25,
        base_speed: 15,
    },
    Species {
        name: "Quagsire",
        base_hp: 95,
        base_attack: 85,
        base_defense: 85,
        base_special_attack: 65,
        base_special_defense: 65,
        base_speed: 35,
    },
    Species {
        name: "Espeon",
        base_hp: 65,
        base_attack: 65,
        base_defense: 60,
        base_special_attack: 130,
        base_special_defense: 95,
        base_speed: 110,
    },
    Species {
        name: "Umbreon",
        base_hp: 95,
        base_attack: 65,
        base_defense: 110,
        base_special_attack: 60,
        base_special_defense: 130,
        base_speed: 65,
    },
    Species {
        name: "Murkrow",
        base_hp: 60,
        base_attack: 85,
        base_defense: 42,
        base_special_attack: 85,
        base_special_defense: 42,
        base_speed: 91,
    },
    Species {
        name: "Slowking",
        base_hp: 95,
        base_attack: 75,
        base_defense: 80,
        base_special_attack: 100,
        base_special_defense: 110,
        base_speed: 30,
    },
    Species {
        name: "Misdreavus",
        base_hp: 60,
        base_attack: 60,
        base_defense: 60,
        base_special_attack: 85,
        base_special_defense: 85,
        base_speed: 85,
    },
    Species {
        name: "Unown",
        base_hp: 48,
        base_attack: 72,
        base_defense: 48,
        base_special_attack: 72,
        base_special_defense: 48,
        base_speed: 48,
    },
    Species {
        name: "Wobbuffet",
        base_hp: 190,
        base_attack: 33,
        base_defense: 58,
        base_special_attack: 33,
        base_special_defense: 58,
        base_speed: 33,
    },
    Species {
        name: "Girafarig",
        base_hp: 70,
        base_attack: 80,
        base_defense: 65,
        base_special_attack: 90,
        base_special_defense: 65,
        base_speed: 85,
    },
    Species {
        name: "Pineco",
        base_hp: 50,
        base_attack: 65,
        base_defense: 90,
        base_special_attack: 35,
        base_special_defense: 35,
        base_speed: 15,
    },
    Species {
        name: "Forretress",
        base_hp: 75,
        base_attack: 90,
        base_defense: 140,
        base_special_attack: 60,
        base_special_defense: 60,
        base_speed: 40,
    },
    Species {
        name: "Dunsparce",
        base_hp: 100,
        base_attack: 70,
        base_defense: 70,
        base_special_attack: 65,
        base_special_defense: 65,
        base_speed: 45,
    },
    Species {
        name: "Gligar",
        base_hp: 65,
        base_attack: 75,
        base_defense: 105,
        base_special_attack: 35,
        base_special_defense: 65,
        base_speed: 85,
    },
    Species {
        name: "Steelix",
        base_hp: 75,
        base_attack: 85,
        base_defense: 200,
        base_special_attack: 55,
        base_special_defense: 65,
        base_speed: 30,
    },
    Species {
        name: "Snubbull",
        base_hp: 60,
        base_attack: 80,
        base_defense: 50,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 30,
    },
    Species {
        name: "Granbull",
        base_hp: 90,
        base_attack: 120,
        base_defense: 75,
        base_special_attack: 60,
        base_special_defense: 60,
        base_speed: 45,
    },
    Species {
        name: "Qwilfish",
        base_hp: 65,
        base_attack: 95,
        base_defense: 75,
        base_special_attack: 55,
        base_special_defense: 55,
        base_speed: 85,
    },
    Species {
        name: "Scizor",
        base_hp: 70,
        base_attack: 130,
        base_defense: 100,
        base_special_attack: 55,
        base_special_defense: 80,
        base_speed: 65,
    },
    Species {
        name: "Shuckle",
        base_hp: 20,
        base_attack: 10,
        base_defense: 230,
        base_special_attack: 10,
        base_special_defense: 230,
        base_speed: 5,
    },
    Species {
        name: "Heracross",
        base_hp: 80,
        base_attack: 125,
        base_defense: 75,
        base_special_attack: 40,
        base_special_defense: 95,
        base_speed: 85,
    },
    Species {
        name: "Sneasel",
        base_hp: 55,
        base_attack: 95,
        base_defense: 55,
        base_special_attack: 35,
        base_special_defense: 75,
        base_speed: 115,
    },
    Species {
        name: "Teddiursa",
        base_hp: 60,
        base_attack: 80,
        base_defense: 50,
        base_special_attack: 50,
        base_special_defense: 50,
        base_speed: 40,
    },
    Species {
        name: "Ursaring",
        base_hp: 90,
        base_attack: 130,
        base_defense: 75,
        base_special_attack: 75,
        base_special_defense: 75,
        base_speed: 55,
    },
    Species {
        name: "Slugma",
        base_hp: 40,
        base_attack: 40,
        base_defense: 40,
        base_special_attack: 70,
        base_special_defense: 40,
        base_speed: 20,
    },
    Species {
        name: "Magcargo",
        base_hp: 50,
        base_attack: 50,
        base_defense: 120,
        base_special_attack: 80,
        base_special_defense: 80,
        base_speed: 30,
    },
    Species {
        name: "Swinub",
        base_hp: 50,
        base_attack: 50,
        base_defense: 40,
        base_special_attack: 30,
        base_special_defense: 30,
        base_speed: 50,
    },
    Species {
        name: "Piloswine",
        base_hp: 100,
        base_attack: 100,
        base_defense: 80,
        base_special_attack: 60,
        base_special_defense: 60,
        base_speed: 50,
    },
    Species {
        name: "Corsola",
        base_hp: 55,
        base_attack: 55,
        base_defense: 85,
        base_special_attack: 65,
        base_special_defense: 85,
        base_speed: 35,
    },
    Species {
        name: "Remoraid",
        base_hp: 35,
        base_attack: 65,
        base_defense: 35,
        base_special_attack: 65,
        base_special_defense: 35,
        base_speed: 65,
    },
    Species {
        name: "Octillery",
        base_hp: 75,
        base_attack: 105,
        base_defense: 75,
        base_special_attack: 105,
        base_special_defense: 75,
        base_speed: 45,
    },
    Species {
        name: "Delibird",
        base_hp: 45,
        base_attack: 55,
        base_defense: 45,
        base_special_attack: 65,
        base_special_defense: 45,
        base_speed: 75,
    },
    Species {
        name: "Mantine",
        base_hp: 65,
        base_attack: 40,
        base_defense: 70,
        base_special_attack: 80,
        base_special_defense: 140,
        base_speed: 70,
    },
    Species {
        name: "Skarmory",
        base_hp: 65,
        base_attack: 80,
        base_defense: 140,
        base_special_attack: 40,
        base_special_defense: 70,
        base_speed: 70,
    },
    Species {
        name: "Houndour",
        base_hp: 45,
        base_attack: 60,
        base_defense: 30,
        base_special_attack: 80,
        base_special_defense: 50,
        base_speed: 65,
    },
    Species {
        name: "Houndoom",
        base_hp: 75,
        base_attack: 90,
        base_defense: 50,
        base_special_attack: 110,
        base_special_defense: 80,
        base_speed: 95,
    },
    Species {
        name: "Kingdra",
        base_hp: 75,
        base_attack: 95,
        base_defense: 95,
        base_special_attack: 95,
        base_special_defense: 95,
        base_speed: 85,
    },
    Species {
        name: "Phanpy",
        base_hp: 90,
        base_attack: 60,
        base_defense: 60,
        base_special_attack: 40,
        base_special_defense: 40,
        base_speed: 40,
    },
    Species {
        name: "Donphan",
        base_hp: 90,
        base_attack: 120,
        base_defense: 120,
        base_special_attack: 60,
        base_special_defense: 60,
        base_speed: 50,
    },
    Species {
        name: "Porygon2",
        base_hp: 85,
        base_attack: 80,
        base_defense: 90,
        base_special_attack: 105,
        base_special_defense: 95,
        base_speed: 60,
    },
    Species {
        name: "Stantler",
        base_hp: 73,
        base_attack: 95,
        base_defense: 62,
        base_special_attack: 85,
        base_special_defense: 65,
        base_speed: 85,
    },
    Species {
        name: "Smeargle",
        base_hp: 55,
        base_attack: 20,
        base_defense: 35,
        base_special_attack: 20,
        base_special_defense: 45,
        base_speed: 75,
    },
    Species {
        name: "Tyrogue",
        base_hp: 35,
        base_attack: 35,
        base_defense: 35,
        base_special_attack: 35,
        base_special_defense: 35,
        base_speed: 35,
    },
    Species {
        name: "Hitmontop",
        base_hp: 50,
        base_attack: 95,
        base_defense: 95,
        base_special_attack: 35,
        base_special_defense: 110,
        base_speed: 70,
    },
    Species {
        name: "Smoochum",
        base_hp: 45,
        base_attack: 30,
        base_defense: 15,
        base_special_attack: 85,
        base_special_defense: 65,
        base_speed: 65,
    },
    Species {
        name: "Elekid",
        base_hp: 45,
        base_attack: 63,
        base_defense: 37,
        base_special_attack: 65,
        base_special_defense: 55,
        base_speed: 95,
    },
    Species {
        name: "Magby",
        base_hp: 45,
        base_attack: 75,
        base_defense: 37,
        base_special_attack: 70,
        base_special_defense: 55,
        base_speed: 83,
    },
    Species {
        name: "Miltank",
        base_hp: 95,
        base_attack: 80,
        base_defense: 105,
        base_special_attack: 40,
        base_special_defense: 70,
        base_speed: 100,
    },
    Species {
        name: "Blissey",
        base_hp: 255,
        base_attack: 10,
        base_defense: 10,
        base_special_attack: 75,
        base_special_defense: 135,
        base_speed: 55,
    },
    Species {
        name: "Raikou",
        base_hp: 90,
        base_attack: 85,
        base_defense: 75,
        base_special_attack: 115,
        base_special_defense: 100,
        base_speed: 115,
    },
    Species {
        name: "Entei",
        base_hp: 115,
        base_attack: 115,
        base_defense: 85,
        base_special_attack: 90,
        base_special_defense: 75,
        base_speed: 100,
    },
    Species {
        name: "Suicune",
        base_hp: 100,
        base_attack: 75,
        base_defense: 115,
        base_special_attack: 90,
        base_special_defense: 115,
        base_speed: 85,
    },
    Species {
        name: "Larvitar",
        base_hp: 50,
        base_attack: 64,
        base_defense: 50,
        base_special_attack: 45,
        base_special_defense: 50,
        base_speed: 41,
    },
    Species {
        name: "Pupitar",
        base_hp: 70,
        base_attack: 84,
        base_defense: 70,
        base_special_attack: 65,
        base_special_defense: 70,
        base_speed: 51,
    },
    Species {
        name: "Tyranitar",
        base_hp: 100,
        base_attack: 134,
        base_defense: 110,
        base_special_attack: 95,
        base_special_defense: 100,
        base_speed: 61,
    },
    Species {
        name: "Lugia",
        base_hp: 106,
        base_attack: 90,
        base_defense: 130,
        base_special_attack: 90,
        base_special_defense: 154,
        base_speed: 110,
    },
    Species {
        name: "Ho-Oh",
        base_hp: 106,
        base_attack: 130,
        base_defense: 90,
        base_special_attack: 110,
        base_special_defense: 154,
        base_speed: 90,
    },
    Species {
        name: "Celebi",
        base_hp: 100,
        base_attack: 100,
        base_defense: 100,
        base_special_attack: 100,
        base_special_defense: 100,
        base_speed: 10,
    },
];

pub const ITEMS: [&str; 255] = [
    "",
    "Master Ball",
    "Ultra Ball",
    "BrightPowder",
    "Great Ball",
    "Poké Ball",
    "Teru-sama",
    "Bicycle",
    "Moon Stone",
    "Antidote",
    "Burn Heal",
    "Ice Heal",
    "Awakening",
    "Parlyz Heal",
    "Full Restore",
    "Max Potion",
    "Hyper Potion",
    "Super Potion",
    "Potion",
    "Escape Rope",
    "Repel",
    "Max Elixer",
    "Fire Stone",
    "Thunderstone",
    "Water Stone",
    "Teru-sama",
    "HP Up",
    "Protein",
    "Iron",
    "Carbos",
    "Lucky Punch",
    "Calcium",
    "Rare Candy",
    "X Accuracy",
    "Leaf Stone",
    "Metal Powder",
    "Nugget",
    "Poké Doll",
    "Full Heal",
    "Revive",
    "Max Revive",
    "Guard Spec.",
    "Super Repel",
    "Max Repel",
    "Dire Hit",
    "Teru-sama",
    "Fresh Water",
    "Soda Pop",
    "Lemonade",
    "X Attack",
    "Teru-sama",
    "X Defend",
    "X Speed",
    "X Special",
    "Coin Case",
    "Itemfinder",
    "Teru-sama",
    "Exp.Share",
    "Old Rod",
    "Good Rod",
    "Silver Leaf",
    "Super Rod",
    "PP Up",
    "Ether",
    "Max Ether",
    "Elixer",
    "Red Scale",
    "SecretPotion",
    "S.S. Ticket",
    "Mystery Egg",
    "Clear Bell*",
    "Silver Wing",
    "Moomoo Milk",
    "Quick Claw",
    "PSNCureBerry",
    "Gold Leaf",
    "Soft Sand",
    "Sharp Beak",
    "PRZCureBerry",
    "Burnt Berry",
    "Ice Berry",
    "Poison Barb",
    "King's Rock",
    "Bitter Berry",
    "Mint Berry",
    "Red Apricorn",
    "TinyMushroom",
    "Big Mushroom",
    "SilverPowder",
    "Blu Apricorn",
    "Teru-sama",
    "Amulet Coin",
    "Ylw Apricorn",
    "Grn Apricorn",
    "Cleanse Tag",
    "Mystic Water",
    "TwistedSpoon",
    "Wht Apricorn",
    "Blackbelt",
    "Blk Apricorn",
    "Teru-sama",
    "Pnk Apricorn",
    "BlackGlasses",
    "SlowpokeTail",
    "Pink Bow",
    "Stick",
    "Smoke Ball",
    "NeverMeltIce",
    "Magnet",
    "MiracleBerry",
    "Pearl",
    "Big Pearl",
    "Everstone",
    "Spell Tag",
    "RageCandyBar",
    "GS Ball*",
    "Blue Card*",
    "Miracle Seed",
    "Thick Club",
    "Focus Band",
    "Teru-sama",
    "EnergyPowder",
    "Energy Root",
    "Heal Powder",
    "Revival Herb",
    "Hard Stone",
    "Lucky Egg",
    "Card Key",
    "Machine Part",
    "Egg Ticket*",
    "Lost Item",
    "Stardust",
    "Star Piece",
    "Basement Key",
    "Pass",
    "Teru-sama",
    "Teru-sama",
    "Teru-sama",
    "Charcoal",
    "Berry Juice",
    "Scope Lens",
    "Teru-sama",
    "Teru-sama",
    "Metal Coat",
    "Dragon Fang",
    "Teru-sama",
    "Leftovers",
    "Teru-sama",
    "Teru-sama",
    "Teru-sama",
    "MysteryBerry",
    "Dragon Scale",
    "Berserk Gene",
    "Teru-sama",
    "Teru-sama",
    "Teru-sama",
    "Sacred Ash",
    "Heavy Ball",
    "Flower Mail",
    "Level Ball",
    "Lure Ball",
    "Fast Ball",
    "Teru-sama",
    "Light Ball",
    "Friend Ball",
    "Moon Ball",
    "Love Ball",
    "Normal Box",
    "Gorgeous Box",
    "Sun Stone",
    "Polkadot Bow",
    "Teru-sama",
    "Up-Grade",
    "Berry",
    "Gold Berry",
    "SquirtBottle",
    "Teru-sama",
    "Park Ball",
    "Rainbow Wing",
    "Teru-sama",
    "Brick Piece",
    "Surf Mail",
    "Litebluemail",
    "Portraitmail",
    "Lovely Mail",
    "Eon Mail",
    "Morph Mail",
    "Bluesky Mail",
    "Music Mail",
    "Mirage Mail",
    "Teru-sama",
    "TM01",
    "TM02",
    "TM03",
    "TM04",
    "TM04",
    "TM05",
    "TM06",
    "TM07",
    "TM08",
    "TM09",
    "TM10",
    "TM11",
    "TM12",
    "TM13",
    "TM14",
    "TM15",
    "TM16",
    "TM17",
    "TM18",
    "TM19",
    "TM20",
    "TM21",
    "TM22",
    "TM23",
    "TM24",
    "TM25",
    "TM26",
    "TM27",
    "TM28",
    "TM28",
    "TM29",
    "TM30",
    "TM31",
    "TM32",
    "TM33",
    "TM34",
    "TM35",
    "TM36",
    "TM37",
    "TM38",
    "TM39",
    "TM40",
    "TM41",
    "TM42",
    "TM43",
    "TM44",
    "TM45",
    "TM46",
    "TM47",
    "TM48",
    "TM49",
    "TM50",
    "HM01",
    "HM02",
    "HM03",
    "HM04",
    "HM05",
    "HM06",
    "HM07",
    "HM08",
    "HM09",
    "HM10",
    "HM11",
    "HM12",
];

pub const MOVES: [&str; 252] = [
    "",
    "Pound",
    "Karate Chop",
    "Double Slap",
    "Comet Punch",
    "Mega Punch",
    "Pay Day",
    "Fire Punch",
    "Ice Punch",
    "Thunder Punch",
    "Scratch",
    "Vise Grip",
    "Guillotine",
    "Razor Wind",
    "Swords Dance",
    "Cut",
    "Gust",
    "Wing Attack",
    "Whirlwind",
    "Fly",
    "Bind",
    "Slam",
    "Vine Whip",
    "Stomp",
    "Double Kick",
    "Mega Kick",
    "Jump Kick",
    "Rolling Kick",
    "Sand Attack",
    "Headbutt",
    "Horn Attack",
    "Fury Attack",
    "Horn Drill",
    "Tackle",
    "Body Slam",
    "Wrap",
    "Take Down",
    "Thrash",
    "Double-Edge",
    "Tail Whip",
    "Poison Sting",
    "Twineedle",
    "Pin Missile",
    "Leer",
    "Bite",
    "Growl",
    "Roar",
    "Sing",
    "Supersonic",
    "Sonic Boom",
    "Disable",
    "Acid",
    "Ember",
    "Flamethrower",
    "Mist",
    "Water Gun",
    "Hydro Pump",
    "Surf",
    "Ice Beam",
    "Blizzard",
    "Psybeam",
    "Bubble Beam",
    "Aurora Beam",
    "Hyper Beam",
    "Peck",
    "Drill Peck",
    "Submission",
    "Low Kick",
    "Counter",
    "Seismic Toss",
    "Strength",
    "Absorb",
    "Mega Drain",
    "Leech Seed",
    "Growth",
    "Razor Leaf",
    "Solar Beam",
    "Poison Powder",
    "Stun Spore",
    "Sleep Powder",
    "Petal Dance",
    "String Shot",
    "Dragon Rage",
    "Fire Spin",
    "Thunder Shock",
    "Thunderbolt",
    "Thunder Wave",
    "Thunder",
    "Rock Throw",
    "Earthquake",
    "Fissure",
    "Dig",
    "Toxic",
    "Confusion",
    "Psychic",
    "Hypnosis",
    "Meditate",
    "Agility",
    "Quick Attack",
    "Rage",
    "Teleport",
    "Night Shade",
    "Mimic",
    "Screech",
    "Double Team",
    "Recover",
    "Harden",
    "Minimize",
    "Smokescreen",
    "Confuse Ray",
    "Withdraw",
    "Defense Curl",
    "Barrier",
    "Light Screen",
    "Haze",
    "Reflect",
    "Focus Energy",
    "Bide",
    "Metronome",
    "Mirror Move",
    "Self-Destruct",
    "Egg Bomb",
    "Lick",
    "Smog",
    "Sludge",
    "Bone Club",
    "Fire Blast",
    "Waterfall",
    "Clamp",
    "Swift",
    "Skull Bash",
    "Spike Cannon",
    "Constrict",
    "Amnesia",
    "Kinesis",
    "Soft-Boiled",
    "High Jump Kick",
    "Glare",
    "Dream Eater",
    "Poison Gas",
    "Barrage",
    "Leech Life",
    "Lovely Kiss",
    "Sky Attack",
    "Transform",
    "Bubble",
    "Dizzy Punch",
    "Spore",
    "Flash",
    "Psywave",
    "Splash",
    "Acid Armor",
    "Crabhammer",
    "Explosion",
    "Fury Swipes",
    "Bonemerang",
    "Rest",
    "Rock Slide",
    "Hyper Fang",
    "Sharpen",
    "Conversion",
    "Tri Attack",
    "Super Fang",
    "Slash",
    "Substitute",
    "Struggle",
    "Sketch",
    "Triple Kick",
    "Thief",
    "Spider Web",
    "Mind Reader",
    "Nightmare",
    "Flame Wheel",
    "Snore",
    "Curse",
    "Flail",
    "Conversion 2",
    "Aeroblast",
    "Cotton Spore",
    "Reversal",
    "Spite",
    "Powder Snow",
    "Protect",
    "Mach Punch",
    "Scary Face",
    "Feint Attack",
    "Sweet Kiss",
    "Belly Drum",
    "Sludge Bomb",
    "Mud-Slap",
    "Octazooka",
    "Spikes",
    "Zap Cannon",
    "Foresight",
    "Destiny Bond",
    "Perish Song",
    "Icy Wind",
    "Detect",
    "Bone Rush",
    "Lock-On",
    "Outrage",
    "Sandstorm",
    "Giga Drain",
    "Endure",
    "Charm",
    "Rollout",
    "False Swipe",
    "Swagger",
    "Milk Drink",
    "Spark",
    "Fury Cutter",
    "Steel Wing",
    "Mean Look",
    "Attract",
    "Sleep Talk",
    "Heal Bell",
    "Return",
    "Present",
    "Frustration",
    "Safeguard",
    "Pain Split",
    "Sacred Fire",
    "Magnitude",
    "Dynamic Punch",
    "Megahorn",
    "Dragon Breath",
    "Baton Pass",
    "Encore",
    "Pursuit",
    "Rapid Spin",
    "Sweet Scent",
    "Iron Tail",
    "Metal Claw",
    "Vital Throw",
    "Morning Sun",
    "Synthesis",
    "Moonlight",
    "Hidden Power",
    "Cross Chop",
    "Twister",
    "Rain Dance",
    "Sunny Day",
    "Crunch",
    "Mirror Coat",
    "Psych Up",
    "Extreme Speed",
    "Ancient Power",
    "Shadow Ball",
    "Future Sight",
    "Rock Smash",
    "Whirlpool",
    "Beat Up",
];
